# Generated by Django 5.2.2 on 2025-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("P", "pending"), ("D", "done")],
                default="P",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
